import{a as b,S as w,i as d}from"./assets/vendor-DEenWwFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&l(p)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const y=e=>` 
    <li class="photo-card">
        <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
            <p>Likes: <span>${e.likes}</span></p>
            <p>Views: <span>${e.views}</span></p>
            <p>Comments: <span>${e.comments}</span></p>
            <p>Downloads: <span>${e.downloads}</span></p>
        </div>
    </li>`,L=15,m=(e,o)=>{const s=new URLSearchParams({key:"48576644-2047f7a262d439c7b8152f8c6",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:L});return b.get(`https://pixabay.com/api/?${s}`)},h=document.querySelector(".form"),u=document.querySelector(".gallery"),a=document.querySelector(".loading"),i=document.querySelector(".load-more");let n=1,c="";const g=15;let f=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:500});const P=async e=>{try{if(e.preventDefault(),u.innerHTML="",i.style.display="none",c=e.currentTarget.elements.query.value.trim(),n=1,c===""){d.show({title:"",backgroundColor:"red",messageColor:"white",position:"topRight",message:"Please enter a search term!"});return}a.style.display="block";const{data:o}=await m(c,n);if(o.total===0){d.show({title:"",backgroundColor:"red",messageColor:"white",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),a.style.display="none";return}u.innerHTML=o.hits.map(s=>y(s)).join(""),f.refresh(),a.style.display="none",o.total>g&&(i.style.display="block"),h.reset()}catch(o){console.log(o),a.style.display="none"}},S=async()=>{try{n+=1,a.style.display="block";const{data:e}=await m(c,n);if(e.hits.length===0){i.style.display="none";return}const o=e.hits.map(l=>y(l)).join("");u.insertAdjacentHTML("beforeend",o),f.refresh(),a.style.display="none";const s=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),n*g>=e.totalHits&&(i.style.display="none",d.show({title:"",backgroundColor:"blue",messageColor:"white",position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.log(e),a.style.display="none"}};h.addEventListener("submit",P);i.addEventListener("click",S);
//# sourceMappingURL=index.js.map
